### ISSUE TITLE
borderless with opengl issues

### ISSUE THREAD

**Issue by skinpop** [melak47/BorderlessWindow#12]
Not sure if this is the right place for my question, but I'll try anyway.

I'm using your method to create a borderless window with an opengl context. It's working but looks different from your example.The shadow seems to expand less from the edge and is almost nonexistent at corners. I'm wondering if this has to do with the calculate proper client size thing you pointed out in the readme. I've experimented but nothing seems to affect the shadow. Since I'm using the entire window for opengl shouldn't it be enough to just pass my desired window dimensions?

[here is a comparison screenshot](http://i.imgur.com/zHniT3x.png), the bottom one is my window.

I have almost no experience with win32 programming so forgive me if I'm doing stupid and the solution is obvious.

**Comment by melak47** [comment]
The comment about the client size is only really relevant for the windowed mode, where you need to account for the window frame and everything taking up space inside the window size you specified.
In borderless mode, a 1280x720 window will have exactly 1280x720 pixels worth of client area.

Hm... Can you run my sample? I'd first check that it actually looks different on your machine - my screenshot is from Windows 10 build 10586.something.

Also, can you compare what it looks like when your window has focus vs. no focus? Regular, bordered windows have a more intense shadow when in focus, but my borderless window does not - I may very well be doing something wrong there.

**Comment by skinpop** [comment]
I disabled the opengl context and used the same settings as your project and ended up with the same result. I'm on win7 so maybe that accounts for the difference. 

Focus state doesn't affect the appearance of the shadow which I also noticed while experimenting. 
I compared the steam client to my window and found that when steam doesn't have focus the shadow is identical to mine, pixel for pixel. It seems like something is missing in terms of enabling the thicker shadow for focused windows.

**Comment by melak47** [comment]
That would be it. If you were on Windows 8, you would instead see a very flat drop-shadow, but then they changed it back on Windows 10...

I think I'm mishandling the `WM_NCACTIVATE` message, unfortunately I don't have a Win7 machine to test on anymore.

If I remove the case handling `WM_NCACTIVATE` from `BorderlessWindow::WndProc`, I get the bigger shadow when in focus, and it resolves some buggy behavior where switching from borderless to windowed leaves the window in a non-focus looking state.

Try removing that case, and click around in the top right corner of the borderless window.
If you may see XP style close/minimize buttons appear, that's the weird behavior I was only seeing on Win7 that I'm not sure how to get rid of.

**Comment by skinpop** [comment]
Removing the case fixed the issue!
If I turn off opengl rendering and keep the frame transparent I get [this](http://i.imgur.com/pABBbG2.png) in the upper corner. The lines match vista/basic buttons. the opengl context renders over that part so it's not a problem for me.

**Comment by melak47** [comment]
Are those buttons clickable? (They shouldn't be, since we don't return any hit regions for them, but who knows...).

Unfortunately it's not as simple on Win10, since I get a border which I can't seem to draw over.

**Comment by skinpop** [comment]
No the buttons aren't clickable. I guess I'll have to test on win 10 to see if it works properly.

**Comment by melak47** [comment]
I finally removed the bad `WM_NACACTIVATE` handling in b2175a4349b437f88219a8fd0742f7f6cdd4e88b, 
and the border can be painted over.
It may be visible briefly resizing the window, though that can be mitigated by using negative margins for `DwmExtendFrameIntoClientArea`. I haven't tested that on Windows 7 yet, though.
