### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by Aeres-u99** [melak47/BorderlessWindow#15]
I was wondering if it is possible to directly obtain the .exe file compiled for both 64-bit and 32-bit.
if not, then how can i create the .exe file so as to install it?

**Comment by melak47** [comment]
I don't have a precompiled release on here, so you'd have to download the project and build it with Visal Studio yourself.

The executable is not really a useful program, though. It just creates a blank, borderless window - I don't know why you'd want to install it.
This project is just intended to demonstrate what WinAPI calls you need to make to create such a window.

**Comment by Aeres-u99** [comment]
Ahh, a borderless window is so much fun :D in windows 7 almost 3-4 pixels in side to side alignment leads wastage of screen space. Its sad that I will have to compile it myself as I donot know anything about visual studio, will it be possible for you to put it in repository? @melak47

**Comment by melak47** [comment]
I'm sorry, but this is not a program for end users, it's a sample for developers.
I'm not gonna make a binary release of a useless demo program.
