### ISSUE TITLE
Noob question: can't think of a good title

### ISSUE THREAD

**Issue by amrbashir** [melak47/BorderlessWindow#16]
The window will be borderless only if `userdata` is passed to `CreateWindowExW` which if I understand correctly is a void pointer to the `BorderlessWindow` object. 

https://github.com/melak47/BorderlessWindow/blob/3b6978d88c0eef47f79c0ac125ec154bf701375c/BorderlessWindow/src/BorderlessWindow.cpp#L105

my noob question is why is that necessary ? 

if I used the following code in a plain `wWinMain`, the window won't be borderless.
```cpp
CreateWindowExW( 
             0, window_class(wndproc), L"Borderless Window", 
             WS_POPUP | WS_THICKFRAME | WS_CAPTION | WS_SYSMENU | WS_MAXIMIZEBOX | WS_MINIMIZEBOX, CW_USEDEFAULT, CW_USEDEFAULT, 
             1280, 720, nullptr, nullptr, nullptr, nullptr
         );
```

**Comment by Blakeinstein** [comment]
From what I understand, according to the docs. Passing "userdata" which is the lpParam , is necessary to send a WM_CREATE message as stated by the documentation available [here](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createwindowexw)

You can see here as to why that is neccesary,
https://github.com/melak47/BorderlessWindow/blob/3b6978d88c0eef47f79c0ac125ec154bf701375c/BorderlessWindow/src/BorderlessWindow.cpp#L147-L152

The `SetWindowLongPtrW` is what I think is setting the window to borderless.

If you are passing null, I think you can sequentially call `::SetWindowLongPtrW(hwnd, GWLP_USERDATA, reinterpret_cast<LONG_PTR>(userdata))` to set the window borderless.

**Comment by amrbashir** [comment]
Unfortunately, I still can't create a borderless window. 
here is my code so far
```cpp

#include <Windows.h>

LRESULT CALLBACK wndProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam)
{
    if (msg == WM_NCCREATE)
    {
        auto userdata = reinterpret_cast<CREATESTRUCTW *>(lParam)->lpCreateParams;
        SetWindowLongPtrW(hwnd, GWLP_USERDATA, reinterpret_cast<LONG_PTR>(userdata));
    }
    return DefWindowProc(hwnd, msg, wParam, lParam);
}
int WINAPI wWinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, PWSTR pCmdLine, int nCmdShow)
{
    WNDCLASS wc = {};
    wc.hInstance = hInstance;
    wc.lpszClassName = "WINDOW_CLASS";
    wc.lpfnWndProc = wndProc;

    RegisterClass(&wc);

    struct UserData
    {
    };

    UserData *userdata = new UserData;

    auto hwnd = CreateWindowExW(
        0, L"WINDOW_CLASS", L"Borderless Window",
        WS_POPUP | WS_THICKFRAME | WS_CAPTION | WS_SYSMENU | WS_MAXIMIZEBOX | WS_MINIMIZEBOX, 100, 100,
        1280, 720, nullptr, nullptr, nullptr, userdata);

    ShowWindow(hwnd, SW_SHOW);

    MSG msg = {0};
    while (GetMessage(&msg, nullptr, NULL, NULL))
    {
        TranslateMessage(&msg);
        DispatchMessage(&msg);
    }

    return 0;
};

```

**Comment by melak47** [comment]
I use the userdata parameter associate the BorderlessWindow instance pointer with the window itself,
so that the window procedure callback can access it. 
This is entirely unrelated to the borderless window creation.

The key things are the choice of window style, and the handling of certain messages in the WndProc.
WM_NCCALCSIZE controls what windows considers the non-client and client area of our window.
By overriding the default behavior here, we can tell it to use the whole window area as the client area.
(See MSDN for details of the parameters to this message).

Handling WM_NCHITTEST tells windows which regions to consider the borders, corners, titlebar and client area, for purposes of resizing and dragging the window.

**Comment by Blakeinstein** [comment]
> WM_NCCALCSIZE controls what windows considers the non-client and client area of our window.

I remember using this in the frameless implementation in Webview-rust. Handling resizable frameless windows is still a pain there.

**Comment by amrbashir** [comment]
Indeed, The missing bit for my minimal example was `return 0` in `WM_NCCALCSIZE` msg.  
Thanks for help guys.
