### ISSUE TITLE
Drag when in the top area in borderless mode

### ISSUE THREAD

**Issue by CybernetHacker14** [melak47/BorderlessWindow#17]
When the window is borderless, the window can be dragged by cursor from anywhere in the client RECT area.
Is there any method in which we can only enable dragging when its within some area from the top?

The reason being, I want to create my own custom title bar (what should be considered as the HTCAPTION area) for windows.

![example](https://user-images.githubusercontent.com/26383905/192132034-9e93e45b-5114-444a-bb17-7309f698e67e.png)
Something like this, I am aiming for.

**Comment by melak47** [comment]
You can make any region you want act like that by returning `HTCAPTION` from `WM_NCHITTEST`.
