### ISSUE TITLE
License file is missing

### ISSUE THREAD

**Issue by sirgru** [melak47/BorderlessWindow#20]
This repo is very useful, code is much simpler and better than some other repos which abstract away window creation. The issue is it's missing a license, and so we cannot assume the code can be used.

**Comment by Calinou** [comment]
@melak47 Bump 🙂

**Comment by melak47** [comment]
Sorry, I didn't see this!

Consider this public domain, I added the CC0 license (doesn't require attribution).
If that doesn't work for you, I'm also happy to license it under MIT or whatever.
