### ISSUE TITLE
Why is main() used instead of winmain()?

### ISSUE THREAD

**Issue by Joshua-Anderson** [melak47/BorderlessWindow#3]
I was wondering why main() is used instead of winmain(). I can't see any advantages to using main over winmain, other than the fact the main is more common outside of the windows api. The advatange to using winmain is that is what vc++ looks for while linking. 

I would advocate for using winmain unless theatre is definite reason for using main because it requires less configuration and is more standard as a example project to be replicated by others.

**Comment by wuxufang** [comment]
Anyway  THX
